---
- name: install gnupg
  apt:
    name: gnupg
    update_cache: yes
  become: yes

- name: add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker
  become: yes

- name: install docker dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - aptitude
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  become: yes

- name: install docker
  apt:
    name: docker-ce
    update_cache: yes
  become: yes
