version: "3.7"

# https://docs.min.io/docs/deploy-minio-on-docker-compose.html
# https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2020-05-08T02-40-49Z
    command: server /data
    ports:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: 12345678
      MINIO_SECRET_KEY: 12345678
    networks:
      default:
        ipv4_address: 172.20.0.2

networks:
  default:
    external:
      name: kubernetes

