version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    network_mode: bridge
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./includes:/etc/nginx/conf.d/includes

