version: '3'

services:
  ldap:
    # https://github.com/osixia/docker-openldap
    # https://hub.docker.com/r/osixia/openldap/tags
    image: osixia/openldap:1.5.0
    container_name: cn_ldap
    hostname: ldap
    command: --copy-service
    ports:
      - "5389:389"
      - "5636:636"
    environment:
      LDAP_ORGANISATION: example
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: password
      LDAP_BASE_DN: dc=example,dc=com
    volumes:
      - ./bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap.ldif
