version: '3'

services:
  prometheus:
    container_name: cn_prometheus
    # https://hub.docker.com/r/prom/prometheus/tags
    image: prom/prometheus:v2.31.1
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
