version: '3'

services:
  postgres:
    # https://hub.docker.com/r/bitnami/postgresql
    image: docker.io/bitnami/postgresql:11
    container_name: cn_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432"

  keycloak:
    # https://hub.docker.com/r/jboss/keycloak/
    image: jboss/keycloak:15.0.2
    container_name: cn_keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
    ports:
      - "127.0.0.1:8882:8080"
    depends_on:
      - postgres

