version: '3'

services:
  gitlab:
    # https://hub.docker.com/r/gitlab/gitlab-ce/tags
    image: gitlab/gitlab-ce:12.9.2-ce.0
    container_name: gitlab
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        registry_external_url 'http://localhost:4567'
        registry['enable'] = true
        gitlab_rails['initial_root_password'] = 'adminadmin'
    ports:
      - '8080:80'
