cluster: null

config:
  images.auto_update_interval: "0"

networks:
- name: lxdbr0
  type: bridge
  config:
    ipv4.address: 10.0.0.1/24
    ipv4.nat: "true"
    ipv6.address: none

storage_pools:
- name: default
  description: default
  config: {}
  driver: dir

profiles:
- name: default
  description: default
  config: {}
  devices:
    root:
      path: /
      pool: default
      type: disk
- name: kubernetes
  description: kubernetes
  config:
    limits.memory.swap: "false"
    linux.kernel_modules: ip_tables,netlink_diag,nf_nat,overlay
    raw.lxc: |
      lxc.apparmor.profile=unconfined
      lxc.cap.drop=
      lxc.cgroup.devices.allow=a
      lxc.mount.auto=proc:rw sys:rw
    security.nesting: "true"
    security.privileged: "true"
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
    aadisable:
      path: /sys/module/nf_conntrack/parameters/hashsize
      source: /sys/module/nf_conntrack/parameters/hashsize
      type: disk
    aadisable1:
      path: /sys/module/apparmor/parameters/enabled
      source: /dev/null
      type: disk
    aadisable2:
      path: /dev/kmsg
      source: /dev/kmsg
      type: disk
