version: "3"

services:
  nginx:
    container_name: cn_nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./includes:/etc/nginx/conf.d/includes

