Vagrant.configure("2") do |config|

  config.vm.define "bastion" do |cfg|
    cfg.vm.hostname = "bastion"

    # https://app.vagrantup.com/boxes/search
    # ~/.vagrant.d/boxes
    cfg.vm.box = "ubuntu/xenial64"

    cfg.vm.box_check_update = false
    cfg.vm.network "private_network", ip: "192.168.33.91"
    # cfg.vm.synced_folder '.', '/vagrant', disabled: true

    cfg.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
      # disable logging
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end

    cfg.vm.provision "shell", :inline => <<END
sudo apt-get update
END
  end


  config.vm.define "gcp" do |cfg|
    cfg.vm.hostname = "gcp"

    # https://app.vagrantup.com/boxes/search
    # ~/.vagrant.d/boxes
    cfg.vm.box = "ubuntu/xenial64"

    cfg.vm.box_check_update = false
    cfg.vm.network "private_network", ip: "192.168.33.91"
    # cfg.vm.synced_folder '.', '/vagrant', disabled: true

    cfg.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
      # disable logging
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end

    cfg.vm.provision "shell", :inline => <<END
sudo apt-get update
END
  end


  config.vm.define "private" do |cfg|
    cfg.vm.hostname = "private"

    # https://app.vagrantup.com/boxes/search
    # ~/.vagrant.d/boxes
    cfg.vm.box = "ubuntu/xenial64"

    cfg.vm.box_check_update = false
    cfg.vm.network "private_network", ip: "192.168.33.92"
    # cfg.vm.synced_folder '.', '/vagrant', disabled: true

    cfg.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
      # disable logging
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end

    cfg.vm.provision "shell", :inline => <<END
sudo apt-get update
END
  end

end
