version: "3"

services:
  vault:
    # https://hub.docker.com/_/vault/
    image: hashicorp/vault:1.8.5
    hostname: vault
    container_name: cn_vault
    ports:
      - "0.0.0.0:8300:8200"
      - "127.0.0.1:8200:8200"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "token"
    # run in memory only
    cap_add:
      - IPC_LOCK

networks:
  default:
    external:
      name: poc
