# https://github.com/hashicorp/vault-helm
# https://github.com/hashicorp/vault-helm/blob/master/values.yaml

server:
  image:
    repository: "hashicorp/vault"
    tag: "1.8.4"

  dataStorage:
    enabled: false

  standalone:
    enabled: "-"
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "file" {
        path = "/vault/data"
      }

