version: "3"

services:
  redis:
    container_name: redis
    # https://registry.hub.docker.com/r/bitnami/redis/tags
    image: bitnami/redis:5.0.14
    ports:
      - '6379'
    environment:
      - REDIS_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no

